project:
  type: book

book:
  title: "RLNotes"
  author: "David Peña Peralta"
  date: "7/11/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - code_tictactoe.qmd
    - multibandits.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



